# This configuration file is designed for benchmarking Zyn's C2S performance.

# Enable console logging for telemetry
# [telemetry.console]
# enabled = true

[c2s-server.limits]
# Maximum number of clients allowed per channel.
max_clients_per_channel = 5000

# Maximum number of inflight requests per client.
max_inflight_requests = 100000

# When running benchmarks locally, set the outbound message queue size to a high value
# to prevent disconnects due to outbound queue overflow.
outbound_message_queue_size = 262144

# Disable rate limiting completely to prevent artificial throughput caps.
rate_limit = 0
