[package]
name = "zyn-protocol"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
once_cell = "1.21.3"
regex = "1.12.2"
tokio = { version = "1.48.0", features = ["io-util"] }
zyn-protocol-macros = { path = "../protocol-macros" }
zyn-util = { path = "../util" }
