[package]
name = "entangle-protocol-macros"
version = "0.3.0"
edition = "2024"
license = "AGPL-3.0-only"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.103"
quote = "1.0.41"
proc-macro2 = "1.0.95"
