[package]
name = "narwhal-protocol-macros"
version = "0.3.0"
edition = "2024"
license = "BSD-3-Clause"

[lib]
proc-macro = true

[dependencies]
syn = "2.0.103"
quote = "1.0.41"
proc-macro2 = "1.0.95"
